### ISSUE TITLE
Invalid regular expression when using --viewport=1920x1080

### ISSUE THREAD

**Issue by opicron** [JarvusInnovations/puppeteer-cli#12]
I am receiving an invalid regular expression error when using the puppeteer-cli 1.5.1 on ubuntu 18.04 LTS.

The result is listed below, why would this error trigger?

`Failed to take screenshot: SyntaxError: Invalid regular expression: /^(?<width>\d+)[xX](?<height>\d+)$/: Invalid group
    at screenshot (/usr/local/lib/node_modules/puppeteer-cli/index.js:153:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by themightychris** [comment]
@opicron can you check what version of node you're running with `node -v` ? Maybe you're running a version of node that does not yet support named capture groups in regular expressions

**Comment by opicron** [comment]
node -v returns 8.10.0

That seems pretty old

**Comment by themightychris** [comment]
Yeah, I'd have thought 18.04 came with something newer, you can follow the node website install instructions to get a newer version from their official repo

That's def an older version that I'm worried about supporting
